export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export PATH="$PATH:$HOME/.poetry/bin"
export PATH="/Users/santera/Library/Python/3.9/bin:$PATH"
export ZDOTDIR="$HOME/.config/zsh"


eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

